
version: '3.8'
services:
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=http://localhost:5000/api
      - REACT_APP_SOCKET_URL=http://localhost:5000
    depends_on:
      - backend
  backend:
    build: ./backend
    ports:
      - "5000:5000"
    environment:
      - PORT=5000
      - MONGO_URI=mongodb+srv://mohitkumar8909647323:jRPiX5TuA50oT0TL@cluster0.9duqepi.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
      - JWT_SECRET=your_jwt_secret
      - CPP_MICROSERVICE_URL=http://localhost:8080
      - REACT_APP_URL=http://localhost:3000
    depends_on:
      - mongo
      - cpp-microservice
  cpp-microservice:
    build: ./cpp-microservice
    ports:
      - "8080:8080"
  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
volumes:
  mongo